 
server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/espm
    username: postgres
    password: Post123321
    driver-class-name: org.postgresql.Driver

  # driverClassName: com.mysql.jdbc.Driver
  # url: jdbc:mysql://localhost:3306/espm
  # username:
  # password:

  # jpa:
  #   show-sql: false
  #   database: postgresql
  #   hibernate:
  #     format_sql: true